

const QRTERMINAL_ADD = "QRTERMINAL_ADD";
const QRTERMINAL_EDIT = "QRTERMINAL_EDIT";
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

export {
    QRTERMINAL_ADD,
    QRTERMINAL_EDIT,
    OPEN_MODAL,
    CLOSE_MODAL
}
